sudo: false

language: node_js
node_js:
  - "0.12.2"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

notifications:
  slack: slackerspace:LtstVlXCibPekCBpSTfP2DDI

install:
  - npm config set registry https://registry.npmjs.org/
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

before_script:
  - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
  - tar -xvf android-sdk_r24.4-linux.tgz
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
  - ionic platform remove android
  - ionic platform add android
  - ionic resources --icon
  - chmod +x hooks/after_prepare/010_add_platform_class.js
  - ionic build android

deploy:
  provider: heroku
  app: btb-ionic
  api_key:
    secure: S0s3wp9BdMRPT5y474dM3K0HCRior/RvEnT31m4TtvTRYx9QZ87QVcxV4eY4pr4U7ZnrCFSZ7T1olqukkhyBFpx8Kf/Sef2plE4GlbCbJG7QUebgAsEbi8M6Ref8Q5MT4+3knYlFWOSqm/Ur2ivoBD/3gjtpDZbGukfMViUZNXjgiBMkQShKAkyvWywtugW6Q1q8DAj6YV9m7QynKhECWr7yAI4nNfrV0OezUhWiTTF/t8qyQLtgRV4lyWmxONkF3StDQ7t9RY9A4e7FUe8+6GFwG7u5dfraLv4bNe3fdn8NIOmx/iVniPGmlrsV52gk42vT6CgVKwfuBvbFwmjrvr+MC3TBYqdPczYd2Jc7KKg7dPL4+42uAf2bpX6iUPGUXIAwJ3sZbEyTta9IIGbwjo3Phhjmdx1UYjlY6z5G9ApxiM3cVlYQLViII/BDMns/9Ua2oulbeAPnkyIRwVZQifZTZGh9RU/J+EBFe/GP2WTCPXDm/PF/6jGgHM4/mhsFaot05n53lWjPtydPgmjyFd10F4K9n/fgV/LzzXkrgjggL2vs4BQIN9o0aNnrloHWTwGI9H81lspvCAvkG5eK86AS3et4NANcDJ5jsKIsYqD+6VHp31bM9Y4ywXIX+pCZK5Kxp32pVQ38xzO9bXbk4q1Znz2b+3LR5NrlgAxBa4Q=